INFO: Starting training:
        Epochs:          5
        Batch size:      2
        Learning rate:   2e-05
        Training size:   9001
        Validation size: 1000
        Checkpoints:     True
        Device:          cuda
        Images scaling:  1.0
        Mixed Precision: False
Epoch 1/5:   0%|                                      | 0/9001 [00:00<?, ?img/s]/root/miniconda3/envs/acnet/lib/python3.8/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Epoch 1/5:   0%|                                      | 0/9001 [00:44<?, ?img/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/acnet/train.py", line 230, in <module>
    train_net(net=net,
  File "/root/autodl-tmp/acnet/train.py", line 143, in train_net
    loss.backward()
  File "/root/autodl-tmp/acnet/train.py", line 143, in train_net
    loss.backward()
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 747, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "/root/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 144, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1147, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1162, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 2173, in <module>
    main()
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 2164, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1476, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/root/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/root/autodl-tmp/acnet/train.py", line 230, in <module>
    train_net(net=net,
  File "/root/miniconda3/envs/acnet/lib/python3.8/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/root/miniconda3/envs/acnet/lib/python3.8/site-packages/torch/serialization.py", line 601, in _save
    storage = storage.cpu()
  File "/root/miniconda3/envs/acnet/lib/python3.8/site-packages/torch/storage.py", line 111, in cpu
    return torch._UntypedStorage(self.size()).copy_(self, False)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
